service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  sync:
    handler: handler.sync
    events:
      - schedule: rate(2 hours)
      - schedule: cron(0 12 * * ? *)
